name: deploy microservice
on:
  push:

permissions:
  packages: write
  contents: read

jobs:
  deploy:
    name: create and deploy container
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.7

      - name: build container
        run: |
          docker build -t ghcr.io/juancamilosalas/microservice/java:latest .
      
      - name: login to ghcr
        run: |
          docker login ghcr.io -u USERNAME -p $GITHUB_TOKEN

      - name: push to registry
        run: |
          docker push ghcr.io/juancamilosalas/microservice/java:latest